# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "gopkg.in/bblfsh/sdk.v2"
  version = "2.2.x"

[prune]
  go-tests = true
  unused-packages = true
